openapi: 3.0.1
info:
  title: OfficeManager Status
  version: 0.1.0
servers:
- url: "{server}:{port}/officeManager/status"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Staff'
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /allLecturers:
    get:
      operationId: getAlllecturers
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /courseLecturer/{searchCourse}:
    get:
      operationId: getCourselecturerSearchcourse
      parameters:
      - name: searchCourse
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /officeLecturer/{officeNumber}:
    get:
      operationId: getOfficelecturerOfficenumber
      parameters:
      - name: officeNumber
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /Lecturer/{staffNumber}:
    get:
      operationId: getLecturerStaffnumber
      parameters:
      - name: staffNumber
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
    delete:
      operationId: deleteLecturerStaffnumber
      parameters:
      - name: staffNumber
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /updateLecturer:
    put:
      operationId: putUpdatelecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Staff'
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    Staff:
      required:
      - courseList
      - officeNumber
      - staffName
      - staffNumber
      - title
      type: object
      properties:
        staffNumber:
          type: integer
          format: int64
        staffName:
          type: string
        title:
          type: string
        officeNumber:
          type: integer
          format: int64
        courseList:
          type: array
          items:
            $ref: '#/components/schemas/CourseList'
    CourseList:
      required:
      - NQFLevel
      - courseCode
      - courseName
      type: object
      properties:
        courseCode:
          type: string
        courseName:
          type: string
        NQFLevel:
          type: integer
          format: int64
